# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5cafed479c068bf44b355642ec7964967567db0d4c4e6c3a3c6d1ba6455403699fdcf7ca8967cec45fd13c6e5c1ba72177a77dd0e9fd0a17618cba17c99094e

test:
  secret_key_base: 32a431030cc84a41701ebc3b0f814af8860b862bfce04699db9cc5c00eac29fb5cb79efafd309e2d0c76d2bd100b7cf620f88c07a8bee074592c0d2d2330101e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
